name: administrator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  
  cupertino_icons: ^1.0.2
 
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  internet_connection_checker_plus: ^2.3.0
  google_maps_flutter: ^2.6.1
  weather: ^3.1.1
  
  http: ^1.2.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  lottie: ^3.1.2
  flutter_dotenv: ^5.1.0
  webview_flutter: ^4.8.0

  aligned_tooltip: ^0.0.1
  auto_size_text: ^3.0.0
  badges: ^2.0.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.5
  cloud_firestore_platform_interface: ^6.1.8
  cloud_firestore_web: ^3.10.7
  collection: ^1.18.0
  dash_chat: 
    git:
      url: https://github.com/FlutterFlow/flutterflow_dash_chat.git

  dropdown_button2: ^2.3.9
  file_picker: ^8.0.5
  firebase_auth: ^4.17.7
  firebase_auth_platform_interface: ^7.1.7
  firebase_auth_web: ^5.9.7
  firebase_core: ^2.26.0
  firebase_core_platform_interface: ^5.0.0
  firebase_core_web: ^2.11.5
  firebase_performance: ^0.9.3+16
  firebase_performance_platform_interface: ^0.1.4+24
  firebase_performance_web: ^0.1.4+24
  fl_chart: ^0.55.0
  flip_card: ^0.7.0
  flutter_animate: ^4.1.1+1
  flutter_cache_manager: ^3.3.1
  flutter_plugin_android_lifecycle: ^2.0.17
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.6.0
  from_css_color: ^2.0.0
  go_router: ^7.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  google_sign_in_android: ^6.1.20

  google_sign_in_platform_interface: ^2.4.2
  google_sign_in_web: ^0.12.1
  image_picker: ^1.1.2
  image_picker_android: ^0.8.8
  image_picker_for_web: ^3.0.1

  image_picker_platform_interface: ^2.9.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  json_path: ^0.6.2
  mime_type: ^1.0.0
  page_transition: ^2.1.0
  path_provider: ^2.0.14
  path_provider_android: ^2.0.25
  path_provider_foundation: ^2.2.2
  path_provider_platform_interface: ^2.0.6
  photo_view: ^0.15.0
  plugin_platform_interface: ^2.1.8
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  shared_preferences_android: ^2.2.1
  shared_preferences_foundation: ^2.3.4
  shared_preferences_platform_interface: ^2.3.1
  shared_preferences_web: ^2.2.1
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.2.6
  stream_transform: ^2.1.0
  text_search: ^1.0.1
  timeago: ^3.2.2
  url_launcher: ^6.2.5
  url_launcher_android: ^6.3.0
  url_launcher_platform_interface: ^2.3.2
  video_player: ^2.9.1
  video_player_android: ^2.4.10
  video_player_avfoundation: ^2.5.1
  video_player_platform_interface: ^6.2.1
  video_player_web: ^2.1.2
  data_table_2: ^2.5.15
  flutter_bloc: ^8.1.6
  dio: ^5.4.3+1
  fluttertoast: ^8.2.6
  firebase_storage: ^11.7.7
  get: ^4.6.6
  get_storage: ^2.1.1
  syncfusion_flutter_charts: 27.1.56
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  # flutter_map_tile_caching: ^9.0.1
  flutter_map_marker_popup: ^6.1.2
  connectivity_plus: ^6.1.0
  share_plus: ^10.0.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  excel: ^4.0.6
  file_saver: ^0.2.13
  syncfusion_flutter_xlsio: ^27.1.56
  firebase_messaging: ^14.9.4
  cloud_functions: ^4.7.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/images/BAYANiLOGO.png
    - lib/images/LOGODESC.png
    - .env
    - assets/images/LOGOAPP.png
    - assets/images/placeholder_image.png
    - assets/images/LOGOAPP.png
    - assets/images/LOGODESC.png
    - assets/images/ICONLAUNCHER.png
    - assets/sounds/emergencynotifsound1.mp3
    - assets/sounds/emergencynotifsound.wav
    - assets/sounds/chatsound.wav